export type Language = "en" | "az" | "ru";

export type TranslationMap = Record<string, string>;

export const translations: Record<Language, TranslationMap> = {
  en: {
    // Common
    "common.brandName": "TurfPro",

    // Header
    "nav.home": "Home",
    "nav.catalog": "Catalog",
    "nav.profile": "Profile",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.logout": "Logout",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",

    // Hero Section
    "hero.title": "Professional Artificial Turf",
    "hero.subtitle": "Installation & Sales",
    "hero.description": "Transform your space with premium artificial grass. Professional installation, free delivery, and lifetime warranty.",
    "hero.cta": "Get Quote",
    "hero.learn": "Learn More",

    // Benefits
    "benefits.title": "Why Choose Our Artificial Turf?",
    "benefits.delivery": "Free Delivery",
    "benefits.delivery.desc": "Free delivery to any location",
    "benefits.warranty": "Lifetime Warranty",
    "benefits.warranty.desc": "Quality guarantee for years",
    "benefits.installation": "Professional Installation",
    "benefits.installation.desc": "Expert installation team",

    // Products
    "products.title": "Our Products",
    "products.residential": "Residential Turf",
    "products.residential.desc": "Perfect for homes and gardens",
    "products.commercial": "Commercial Turf",
    "products.commercial.desc": "Durable for high traffic areas",
    "products.sports": "Sports Turf",
    "products.sports.desc": "Professional grade for stadiums",
    "products.order": "Order Now",
    "products.details": "View Details",
    "products.addToCart": "Add to Cart",

    // Order Form
    "order.title": "Order Artificial Turf",
    "order.product": "Selected Product",
    "order.area": "Area (m²)",
    "order.installation": "Installation Service",
    "order.installation.yes": "Yes (+$15/m²)",
    "order.installation.no": "No",
    "order.delivery": "Delivery Address",
    "order.phone": "Phone Number",
    "order.email": "Email",
    "order.total": "Total Cost",
    "order.submit": "Place Order",
    "order.success": "Order placed successfully!",

    // Auth additional
    "auth.welcomeBack": "Welcome back",
    "auth.createAccount": "Create your account",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.testAdmin": "Test Admin",
    "auth.anyPassword": "Any password (min 6 chars)",
    "auth.confirmPassword": "Confirm Password",

    // Catalog
    "catalog.title": "Artificial Turf Catalog",
    "catalog.subtitle": "Find the perfect turf for your needs",
    "catalog.filters": "Filters",
    "catalog.search": "Search",
    "catalog.searchPlaceholder": "Search products...",
    "catalog.category": "Category",
    "catalog.allCategories": "All Categories",
    "catalog.landscape": "Landscape",
    "catalog.sports": "Sports",
    "catalog.decorative": "Decorative",
    "catalog.priceRange": "Price per m² (₽)",
    "catalog.sort": "Sort",
    "catalog.sortName": "By Name",
    "catalog.sortPriceLow": "Price: Low to High",
    "catalog.sortPriceHigh": "Price: High to Low",
    "catalog.sortPopular": "Popular",
    "catalog.resetFilters": "Reset Filters",
    "catalog.productsFound": "Products found",
    "catalog.noProducts": "No products found",
    "catalog.from": "from",
    "catalog.height": "Pile Height",
    "catalog.density": "Density",
    "catalog.warranty": "Warranty",
    "catalog.moreDetails": "More Details",

    // Cart additional
    "cart.emptyMessage": "Add products to cart to place an order",
    "cart.continueShopping": "Continue Shopping",
    "cart.clearCart": "Clear Cart",
    "cart.area": "Area",
    "cart.installationIncluded": "Installation included",
    "cart.turf": "Turf",
    "cart.installation": "Installation",
    "cart.orderSummary": "Order Summary",
    "cart.items": "Items",
    "cart.freeDelivery": "Free",
    "cart.delivery": "Delivery",
    "cart.orderTotal": "Total",
    "cart.placeOrder": "Place Order",
    "cart.terms": 'By clicking "Place Order", you agree to the terms of service',
    "cart.additionalNotes": "Additional Notes",

    // Profile additional
    "profile.personalCabinet": "Personal Cabinet",
    "profile.manageProfile": "Manage your profile and orders",
    "profile.profileInfo": "Profile Information",
    "profile.name": "Name",
    "profile.registrationDate": "Registration Date",
    "profile.editProfile": "Edit Profile",
    "profile.statistics": "Statistics",
    "profile.itemsInCart": "Items in Cart",
    "profile.totalOrderAmount": "Total Order Amount",
    "profile.goToCatalog": "Go to Catalog",
    "profile.goToCart": "Go to Cart",
    "profile.noOrdersYet": "You don't have any orders yet",
    "profile.placeFirstOrder": "Place your first order in our catalog",
    "profile.orderNumber": "Order",
    "profile.orderItems": "Items",
    "profile.deliveryAddress": "Delivery Address",
    "profile.additionalWishes": "Additional Wishes",
    "profile.contact": "Contact",
    "profile.freeDelivery": "Free delivery",

    // Admin additional
    "admin.accessDenied": "Access Denied",
    "admin.noAdminRights": "You don't have admin panel access rights",
    "admin.goHome": "Go Home",
    "admin.adminPanel": "Admin Panel",
    "admin.manageProducts": "Manage products, orders and users",
    "admin.totalProducts": "Total Products",
    "admin.totalOrders": "Total Orders",
    "admin.pendingOrders": "Pending Orders",
    "admin.totalRevenue": "Total Revenue",
    "admin.productManagement": "Product Management",
    "admin.addProduct": "Add Product",
    "admin.editProduct": "Edit Product",
    "admin.productName": "Product Name",
    "admin.price": "Price (₽/m²)",
    "admin.description": "Description",
    "admin.imageUrl": "Image URL",
    "admin.pileHeight": "Pile Height",
    "admin.popular": "Popular",
    "admin.premium": "Premium",
    "admin.update": "Update",
    "admin.confirmDelete": "Are you sure you want to delete this product?",
    "admin.productUpdated": "Product updated!",
    "admin.productAdded": "Product added!",
    "admin.productDeleted": "Product deleted!",
    "admin.orderManagement": "Order Management",
    "admin.customer": "Customer",
    "admin.changeStatus": "Change Status",
    "admin.confirm": "Confirm",
    "admin.inProgress": "In Progress",
    "admin.completed": "Completed",
    "admin.cancelled": "Cancelled",
    "admin.statusUpdated": "Order status updated!",
    "admin.userManagement": "User Management",
    "admin.registration": "Registration",
    "admin.ordersCount": "Orders",

    // Status
    "status.pending": "Pending Confirmation",
    "status.confirmed": "Confirmed",
    "status.inProgress": "In Progress",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
  },

  az: {
    // Common
    "common.brandName": "TurfPro",

    // Header
    "nav.home": "Ana səhifə",
    "nav.catalog": "Kataloq",
    "nav.profile": "Profil",
    "nav.admin": "Admin",
    "nav.login": "Giriş",
    "nav.register": "Qeydiyyat",
    "nav.logout": "Çıxış",
    "nav.services": "Servis",
    "nav.about": "Haqqımızda",
    "nav.contact": "Əlaqə",

    // Hero Section
    "hero.title": "Peşəkar Süni Çəmən",
    "hero.subtitle": "Quraşdırma və Satış",
    "hero.description": "Yüksək keyfiyyətli süni çəmənlə məkanınızı dəyişdirin. Peşəkar quraşdırma, pulsuz çatdırılma və ömürlük zəmanət.",
    "hero.cta": "Qiymət Al",
    "hero.learn": "Ətraflı",

    // Benefits
    "benefits.title": "Niyə Bizim Süni Çəməni Seçməlisiniz?",
    "benefits.delivery": "Pulsuz Çatdırılma",
    "benefits.delivery.desc": "İstənilən yerə pulsuz çatdırılma",
    "benefits.warranty": "Ömürlük Zəmanət",
    "benefits.warranty.desc": "İllər boyu keyfiyyət təminatı",
    "benefits.installation": "Peşəkar Quraşdırma",
    "benefits.installation.desc": "Mütəxəssis quraşdırma komandası",

    // Products
    "products.title": "Məhsullarımız",
    "products.residential": "Yaşayış Çəməni",
    "products.residential.desc": "Evlər və bağlar üçün mükəmməl",
    "products.commercial": "Kommersiya Çəməni",
    "products.commercial.desc": "Yüksək trafikli sahələr üçün davamlı",
    "products.sports": "İdman Çəməni",
    "products.sports.desc": "Stadionlar üçün peşəkar səviyyə",
    "products.order": "İndi Sifariş Ver",
    "products.details": "Təfərrüatları Gör",
    "products.addToCart": "Səbətə Əlavə Et",

    // Order Form
    "order.title": "Süni Çəmən Sifarişi",
    "order.product": "Seçilmiş Məhsul",
    "order.area": "Sahə (m²)",
    "order.installation": "Quraşdırma Xidməti",
    "order.installation.yes": "Bəli (+$15/m²)",
    "order.installation.no": "Xeyr",
    "order.delivery": "Çatdırılma Ünvanı",
    "order.phone": "Telefon Nömrəsi",
    "order.email": "Email",
    "order.total": "Ümumi Məbləğ",
    "order.submit": "Sifarişi Yerləşdir",
    "order.success": "Sifariş uğurla yerləşdirildi!",

    // Auth additional
    "auth.welcomeBack": "Xoş gəlmisiniz",
    "auth.createAccount": "Hesabınızı yaradın",
    "auth.noAccount": "Hesabınız yoxdur?",
    "auth.haveAccount": "Artıq hesabınız var?",
    "auth.testAdmin": "Test Admin",
    "auth.anyPassword": "İstənilən şifrə (min 6 simvol)",
    "auth.confirmPassword": "Şifrəni Təsdiqləyin",

    // Catalog
    "catalog.title": "Süni Çəmən Kataloqu",
    "catalog.subtitle": "Ehtiyaclarınıza uyğun çəməni tapın",
    "catalog.filters": "Filtrlər",
    "catalog.search": "Axtarış",
    "catalog.searchPlaceholder": "Məhsulları axtar...",
    "catalog.category": "Kateqoriya",
    "catalog.allCategories": "Bütün Kateqoriyalar",
    "catalog.landscape": "Landskap",
    "catalog.sports": "İdman",
    "catalog.decorative": "Dekorativ",
    "catalog.priceRange": "Qiymət (₽/m²)",
    "catalog.sort": "Sıralama",
    "catalog.sortName": "Ad üzrə",
    "catalog.sortPriceLow": "Qiymət: Aşağıdan Yüksəyə",
    "catalog.sortPriceHigh": "Qiymət: Yüksəkdən Aşağıya",
    "catalog.sortPopular": "Populyar",
    "catalog.resetFilters": "Filtrləri Sıfırla",
    "catalog.productsFound": "Məhsullar tapıldı",
    "catalog.noProducts": "Məhsul tapılmadı",
    "catalog.from": "dən",
    "catalog.height": "Yükseklik",
    "catalog.density": "Sıxlıq",
    "catalog.warranty": "Zəmanət",
    "catalog.moreDetails": "Ətraflı",

    // Cart additional
    "cart.emptyMessage": "Sifariş vermək üçün məhsulları səbətə əlavə edin",
    "cart.continueShopping": "Alışa Davam Et",
    "cart.clearCart": "Səbəti Təmizlə",
    "cart.area": "Sahə",
    "cart.installationIncluded": "Quraşdırma daxildir",
    "cart.turf": "Çəmən",
    "cart.installation": "Quraşdırma",
    "cart.orderSummary": "Sifariş Xülasəsi",
    "cart.items": "Məhsullar",
    "cart.freeDelivery": "Pulsuz",
    "cart.delivery": "Çatdırılma",
    "cart.orderTotal": "Ümumi",
    "cart.placeOrder": "Sifarişi Yerləşdir",
    "cart.terms": '"Sifarişi Yerləşdir" düyməsini klikləməklə siz xidmət şərtlərini qəbul edirsiniz',
    "cart.additionalNotes": "Əlavə Qeydlər",

    // Profile additional
    "profile.personalCabinet": "Şəxsi Kabinet",
    "profile.manageProfile": "Profil və sifarişlərinizi idarə edin",
    "profile.profileInfo": "Profil Məlumatı",
    "profile.name": "Ad",
    "profile.registrationDate": "Qeydiyyat Tarixi",
    "profile.editProfile": "Profili Redaktə Et",
    "profile.statistics": "Statistika",
    "profile.itemsInCart": "Səbətdə Məhsullar",
    "profile.totalOrderAmount": "Ümumi Sifariş Məbləği",
    "profile.goToCatalog": "Kataloqa Get",
    "profile.goToCart": "Səbətə Get",
    "profile.noOrdersYet": "Hələ sifarişiniz yoxdur",
    "profile.placeFirstOrder": "İlk sifarişinizi kataloqumuzdan verin",
    "profile.orderNumber": "Sifariş",
    "profile.orderItems": "Məhsullar",
    "profile.deliveryAddress": "Çatdırılma Ünvanı",
    "profile.additionalWishes": "Əlavə Arzular",
    "profile.contact": "Əlaqə",
    "profile.freeDelivery": "Pulsuz çatdırılma",

    // Admin additional
    "admin.accessDenied": "Giriş Qadağan Edildi",
    "admin.noAdminRights": "Admin panelinə giriş icazəniz yoxdur",
    "admin.goHome": "Ana Səhifəyə Get",
    "admin.adminPanel": "Admin Paneli",
    "admin.manageProducts": "Məhsullar, sifarişlər və istifadəçiləri idarə et",
    "admin.totalProducts": "Ümumi Məhsullar",
    "admin.totalOrders": "Ümumi Sifarişlər",
    "admin.pendingOrders": "Gözləyən Sifarişlər",
    "admin.totalRevenue": "Ümumi Gəlir",
    "admin.productManagement": "Məhsul İdarəsi",
    "admin.addProduct": "Məhsul Əlavə Et",
    "admin.editProduct": "Məhsulu Redaktə Et",
    "admin.productName": "Məhsul Adı",
    "admin.price": "Qiymət (₽/m²)",
    "admin.description": "Təsvir",
    "admin.imageUrl": "Şəkil URL",
    "admin.pileHeight": "Yükseklik",
    "admin.popular": "Populyar",
    "admin.premium": "Premium",
    "admin.update": "Yenilə",
    "admin.confirmDelete": "Bu məhsulu silmək istədiyinizə əminsiniz?",
    "admin.productUpdated": "Məhsul yeniləndi!",
    "admin.productAdded": "Məhsul əlavə edildi!",
    "admin.productDeleted": "Məhsul silindi!",
    "admin.orderManagement": "Sifariş İdarəsi",
    "admin.customer": "Müştəri",
    "admin.changeStatus": "Statusu Dəyiş",
    "admin.confirm": "Təsdiq et",
    "admin.inProgress": "Davam edir",
    "admin.completed": "Tamamlandı",
    "admin.cancelled": "Ləğv edildi",
    "admin.statusUpdated": "Sifariş statusu yeniləndi!",
    "admin.userManagement": "İstifadəçi İdarəsi",
    "admin.registration": "Qeydiyyat",
    "admin.ordersCount": "Sifarişlər",

    // Status
    "status.pending": "Təsdiq gözləyir",
    "status.confirmed": "Təsdiqləndi",
    "status.inProgress": "Davam edir",
    "status.completed": "Tamamlandı",
    "status.cancelled": "Ləğv edildi",
  },

  ru: {
    // Common
    "common.brandName": "TurfPro",

    // Header
    "nav.home": "Главная",
    "nav.catalog": "Каталог",
    "nav.profile": "Профиль",
    "nav.admin": "Админ",
    "nav.login": "Вход",
    "nav.register": "Регистрация",
    "nav.logout": "Выход",
    "nav.services": "Сервисы",
    "nav.about": "О нас",
    "nav.contact": "Контакты",

    // Hero Section
    "hero.title": "Профессиональный Искусственный Газон",
    "hero.subtitle": "Установка и Продажа",
    "hero.description": "Преобразите ваше пространство с премиальным искусственным газоном. Профессиональная установка, бесплатная доставка и пожизненная гарантия.",
    "hero.cta": "Получить Цену",
    "hero.learn": "Подробнее",

    // Benefits
    "benefits.title": "Почему Выбирают Наш Искусственный Газон?",
    "benefits.delivery": "Бесплатная Доставка",
    "benefits.delivery.desc": "Бесплатная доставка в любую точку",
    "benefits.warranty": "Пожизненная Гарантия",
    "benefits.warranty.desc": "Гарантия качества на годы",
    "benefits.installation": "Профессиональная Установка",
    "benefits.installation.desc": "Команда экспертов по установке",

    // Products
    "products.title": "Наши Продукты",
    "products.residential": "Жилой Газон",
    "products.residential.desc": "Идеально для домов и садов",
    "products.commercial": "Коммерческий Газон",
    "products.commercial.desc": "Прочный для мест с высокой проходимостью",
    "products.sports": "Спортивный Газон",
    "products.sports.desc": "Профессиональный уровень для стадионов",
    "products.order": "Заказать Сейчас",
    "products.details": "Подробнее",
    "products.addToCart": "В корзину",

    // Order Form
    "order.title": "Заказать Искусственный Газон",
    "order.product": "Выбранный продукт",
    "order.area": "Площадь (м²)",
    "order.installation": "Услуга Установки",
    "order.installation.yes": "Да (+$15/м²)",
    "order.installation.no": "Нет",
    "order.delivery": "Адрес Доставки",
    "order.phone": "Номер Телефона",
    "order.email": "Email",
    "order.total": "Итоговая Сумма",
    "order.submit": "Оформить Заказ",
    "order.success": "Заказ успешно размещён!",

    // Auth additional
    "auth.welcomeBack": "С возвращением",
    "auth.createAccount": "Создайте аккаунт",
    "auth.noAccount": "Нет аккаунта?",
    "auth.haveAccount": "Уже есть аккаунт?",
    "auth.testAdmin": "Тест Админ",
    "auth.anyPassword": "Любой пароль (мин 6 символов)",
    "auth.confirmPassword": "Подтвердите пароль",

    // Catalog
    "catalog.title": "Каталог Искусственного Газона",
    "catalog.subtitle": "Найдите идеальный газон для своих нужд",
    "catalog.filters": "Фильтры",
    "catalog.search": "Поиск",
    "catalog.searchPlaceholder": "Поиск продуктов...",
    "catalog.category": "Категория",
    "catalog.allCategories": "Все Категории",
    "catalog.landscape": "Ландшафт",
    "catalog.sports": "Спорт",
    "catalog.decorative": "Декоративный",
    "catalog.priceRange": "Цена за м² (₽)",
    "catalog.sort": "Сортировка",
    "catalog.sortName": "По имени",
    "catalog.sortPriceLow": "Цена: по возрастанию",
    "catalog.sortPriceHigh": "Цена: по убыванию",
    "catalog.sortPopular": "Популярные",
    "catalog.resetFilters": "Сбросить фильтры",
    "catalog.productsFound": "Найдено продуктов",
    "catalog.noProducts": "Продукты не найдены",
    "catalog.from": "от",
    "catalog.height": "Высота ворса",
    "catalog.density": "Плотность",
    "catalog.warranty": "Гарантия",
    "catalog.moreDetails": "Подробнее",

    // Cart additional
    "cart.emptyMessage": "Добавьте продукты в корзину для оформления заказа",
    "cart.continueShopping": "Продолжить покупки",
    "cart.clearCart": "Очистить корзину",
    "cart.area": "Площадь",
    "cart.installationIncluded": "Установка включена",
    "cart.turf": "Газон",
    "cart.installation": "Установка",
    "cart.orderSummary": "Итог заказа",
    "cart.items": "Товары",
    "cart.freeDelivery": "Бесплатно",
    "cart.delivery": "Доставка",
    "cart.orderTotal": "Итого",
    "cart.placeOrder": "Оформить заказ",
    "cart.terms": 'Нажимая "Оформить заказ", вы соглашаетесь с условиями обслуживания',
    "cart.additionalNotes": "Дополнительные заметки",

    // Profile additional
    "profile.personalCabinet": "Личный кабинет",
    "profile.manageProfile": "Управляйте профилем и заказами",
    "profile.profileInfo": "Информация о профиле",
    "profile.name": "Имя",
    "profile.registrationDate": "Дата регистрации",
    "profile.editProfile": "Редактировать профиль",
    "profile.statistics": "Статистика",
    "profile.itemsInCart": "Товары в корзине",
    "profile.totalOrderAmount": "Общая сумма заказов",
    "profile.goToCatalog": "Перейти в каталог",
    "profile.goToCart": "Перейти в корзину",
    "profile.noOrdersYet": "У вас еще нет заказов",
    "profile.placeFirstOrder": "Сделайте первый заказ в нашем каталоге",
    "profile.orderNumber": "Заказ",
    "profile.orderItems": "Товары",
    "profile.deliveryAddress": "Адрес доставки",
    "profile.additionalWishes": "Дополнительные пожелания",
    "profile.contact": "Контакт",
    "profile.freeDelivery": "Бесплатная доставка",

    // Admin additional
    "admin.accessDenied": "Доступ запрещен",
    "admin.noAdminRights": "У вас нет прав доступа к админ-панели",
    "admin.goHome": "На главную",
    "admin.adminPanel": "Админ Панель",
    "admin.manageProducts": "Управление продуктами, заказами и пользователями",
    "admin.totalProducts": "Всего продуктов",
    "admin.totalOrders": "Всего заказов",
    "admin.pendingOrders": "Ожидающие заказы",
    "admin.totalRevenue": "Общий доход",
    "admin.productManagement": "Управление продуктами",
    "admin.addProduct": "Добавить продукт",
    "admin.editProduct": "Редактировать продукт",
    "admin.productName": "Название продукта",
    "admin.price": "Цена (₽/м²)",
    "admin.description": "Описание",
    "admin.imageUrl": "URL изображения",
    "admin.pileHeight": "Высота ворса",
    "admin.popular": "Популярный",
    "admin.premium": "Премиум",
    "admin.update": "Обновить",
    "admin.confirmDelete": "Вы уверены, что хотите удалить этот продукт?",
    "admin.productUpdated": "Продукт обновлён!",
    "admin.productAdded": "Продукт добавлен!",
    "admin.productDeleted": "Продукт удалён!",
    "admin.orderManagement": "Управление заказами",
    "admin.customer": "Клиент",
    "admin.changeStatus": "Изменить статус",
    "admin.confirm": "Подтвердить",
    "admin.inProgress": "В процессе",
    "admin.completed": "Завершён",
    "admin.cancelled": "Отменён",
    "admin.statusUpdated": "Статус заказа обновлён!",
    "admin.userManagement": "Управление пользователями",
    "admin.registration": "Регистрация",
    "admin.ordersCount": "Заказы",

    // Status
    "status.pending": "Ожидает подтверждения",
    "status.confirmed": "Подтверждён",
    "status.inProgress": "В процессе",
    "status.completed": "Завершён",
    "status.cancelled": "Отменён",
  },
};
